# Generated by Django 3.2 on 2021-04-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_profile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
