# Generated by Django 3.1 on 2021-05-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20210429_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
