# Generated by Django 3.2 on 2021-04-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('avg_score', models.PositiveIntegerField()),
            ],
        ),
    ]
