# Generated by Django 3.2 on 2021-04-15 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('standard', models.PositiveSmallIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='avg_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_scored', models.IntegerField(default=0)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=1024)),
                ('solution_id', models.CharField(max_length=255)),
                ('mark', models.PositiveIntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.exam')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.subject'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.question')),
            ],
        ),
    ]
