# Generated by Django 3.2 on 2021-04-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20210415_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='solution_id',
            new_name='solution',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='exam_id',
            new_name='exam',
        ),
    ]
