# Generated by Django 3.2 on 2021-04-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_auto_20210419_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='exam_id',
            new_name='exam',
        ),
    ]
