# Generated by Django 3.2 on 2021-04-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_rename_exam_id_question_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='solution',
            new_name='solution_id',
        ),
    ]
