# Generated by Django 3.2 on 2021-04-25 23:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0007_submittedquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmittedQuestions',
            new_name='SubmittedQuestion',
        ),
    ]
