# Generated by Django 3.2 on 2021-04-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_rename_submittedquestions_submittedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
