# Generated by Django 3.2 on 2021-04-27 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='is_ongoing',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='time_given',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
