# Generated by Django 3.2 on 2021-04-27 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20210427_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='time_given',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='time_started',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 8, 58, 58, 849524, tzinfo=utc)),
        ),
    ]
