# Generated by Django 3.2 on 2021-04-27 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20210427_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='time_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
