# Generated by Django 3.1 on 2021-04-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20210429_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedanswer',
            old_name='submitted_answer',
            new_name='answer',
        ),
    ]
